name: cd-test

on:
  workflow_dispatch:

jobs:
  build:
    name: cd-test
    runs-on: split-runner
    
    steps:
    - name: find now
      run: pwd
    - name: Checkout Source Code
      uses: actions/checkout@v2
      with:
        ssh-key: ${{ secrets.SSH }}
        submodules: 'recursive'
    - name: check branch
      run: git branch -a
    - name: check git log
      run: git log --oneline
      
